!include https://raw.githubusercontent.com/mcpride/C4-PlantumlSkin/mcpride_master/src/general/general.puml
!include https://raw.githubusercontent.com/mcpride/C4-PlantumlSkin/mcpride_master/src/general/legend.puml
!include https://raw.githubusercontent.com/mcpride/C4-PlantumlSkin/mcpride_master/src/general/notes.puml

!include https://raw.githubusercontent.com/mcpride/C4-PlantumlSkin/mcpride_master/src/items/actors.puml
!include https://raw.githubusercontent.com/mcpride/C4-PlantumlSkin/mcpride_master/src/items/components.puml
!include https://raw.githubusercontent.com/mcpride/C4-PlantumlSkin/mcpride_master/src/items/containers.puml
!include https://raw.githubusercontent.com/mcpride/C4-PlantumlSkin/mcpride_master/src/items/dbs.puml
!include https://raw.githubusercontent.com/mcpride/C4-PlantumlSkin/mcpride_master/src/items/expanded.puml
!include https://raw.githubusercontent.com/mcpride/C4-PlantumlSkin/mcpride_master/src/items/misc.puml
!include https://raw.githubusercontent.com/mcpride/C4-PlantumlSkin/mcpride_master/src/items/queues.puml
!include https://raw.githubusercontent.com/mcpride/C4-PlantumlSkin/mcpride_master/src/items/systems.puml
!include https://raw.githubusercontent.com/mcpride/C4-PlantumlSkin/mcpride_master/src/items/sequence.puml
